### ISSUE TITLE
More complete wrapper...

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#1]
Excellent work. There are a few extra functions you may want to support.

``roaring_bitmap_or_many`` : https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring.h#L84

As well as, possibly, the basic serialization functions such as ``roaring_bitmap_portable_deserialize``, ``roaring_bitmap_portable_serialize``.

**Comment by Ezibenroc** [comment]
Thank you for your suggestions.
See https://github.com/Ezibenroc/PyRoaringBitMap/commit/654621d4b54afdc3ec751ef8a786a6424cf82871 and https://github.com/Ezibenroc/PyRoaringBitMap/commit/90e4761ae01b22bcc0bc44b60bf3f6942e876ece .

Do you think it is better to use the function `roaring_bitmap_or_many` or `roaring_bitmap_or_many_heap`? It is said that the second can be faster. Is it often the case? Can it be slower?

There seems to be a bug in the serialization, c.f. [this issue](https://github.com/RoaringBitmap/CRoaring/issues/31).

**Comment by lemire** [comment]
@Ezibenroc  I would recommend the ``roaring_bitmap_portable_serialize`` and ``roaring_bitmap_portable_deserialize`` functions for the time being. They use a format that is used by other libraries. The other serialization functions are more experimental and subject to change (whereas the portable ones won't change, unless there is a bug).

I recommend `` roaring_bitmap_or_many`` for the time being. It is not always fastest but it will almost always use less memory.

**Comment by Ezibenroc** [comment]
Thanks. I switched to `roaring_bitmap_portable_serialize` and `roaring_bitmap_portable_deserialize` (https://github.com/Ezibenroc/PyRoaringBitMap/commit/cb9bae2658578934265bca06610f381e36d32df3), and I kept `roaring_bitmap_or_many`.
