### ISSUE TITLE
Find a faster way to do a list constructor

### ISSUE THREAD

**Issue by Ezibenroc** [Ezibenroc/PyRoaringBitMap#10]
The current list constructor is very slow, even with no checks performed on the data.
Most of the time is spent on the call `values = (ctypes.c_uint32 * size)(*values)`, as shown by this modified `pyroaring.py`:

```python
    def __init__(self, values=None, obj=None):
        t = time.time()
        size = len(values)
        print('size                  :   %fs' % (time.time()-t))
        t = time.time()
        values = (ctypes.c_uint32 * size)(*values)
        print('c_array               :   %fs' % (time.time()-t))
        t = time.time()
        self.__obj__ = libroaring.roaring_bitmap_of_ptr(size, values)
        print('croaring.of_ptr       :   %fs' % (time.time()-t))
        t = time.time()
        libroaring.roaring_bitmap_run_optimize(self.__obj__)
        print('croaring.run_optimize :   %fs' % (time.time()-t))
        t = time.time()
```

```python
from pyroaring import BitMap

l = list(range(100000000))
bm = BitMap(l)
```
Gives:
```
size                  :   0.000005s
c_array               :   17.886208s
croaring.of_ptr       :   3.518115s
croaring.run_optimize :   0.013420s
```

As a comparison, creating a `set` with the same list (i.e. calling `set(l)`) takes a time of 3.7s.

**Comment by lemire** [comment]
Yes, for some reason conversion to an array in Python is really slow:

```python
import timeit
setup="from array import array; import ctypes; t = [i for i in range(1024)];"
print(timeit.timeit(stmt='(ctypes.c_uint32 * len(t))(*t)',setup=setup,number=100))
print(timeit.timeit(stmt='array("I",t)',setup=setup,number=100))
print(timeit.timeit(stmt='set(t)',setup=setup,number=100))
```

```bash
$ python3 convert.py
0.024186760070733726
0.0013164669508114457
0.0022085349773988128
```

I have spent some time on the issue and I cannot understand why it is so slow.

**Comment by lemire** [comment]
I think it could be worthwhile to try a tool like ``perf`` under Linux to see which instructions are eating up all this time.

**Comment by Ezibenroc** [comment]
I get similar results with your code.
I tried to run it with perf. Here are the results when `t` is a list of 1000000 integers:
**ctypes**

     Performance counter stats for 'python3 perf.py':

           1807,891637      task-clock (msec)         #    1,000 CPUs utilized          
                     8      context-switches          #    0,004 K/sec                  
                     0      cpu-migrations            #    0,000 K/sec                  
                59 523      page-faults               #    0,033 M/sec                  
         5 755 704 178      cycles                    #    3,184 GHz                    
        13 552 506 138      instructions              #    2,35  insn per cycle         
         3 217 289 822      branches                  # 1779,581 M/sec                  
               748 614      branch-misses             #    0,02% of all branches        

           1,808349671 seconds time elapsed

**array**

     Performance counter stats for 'python3 perf.py':

            144,678718      task-clock (msec)         #    0,998 CPUs utilized          
                     0      context-switches          #    0,000 K/sec                  
                     0      cpu-migrations            #    0,000 K/sec                  
                12 913      page-faults               #    0,089 M/sec                  
           458 284 661      cycles                    #    3,168 GHz                    
         1 253 747 066      instructions              #    2,74  insn per cycle         
           325 528 639      branches                  # 2250,011 M/sec                  
               708 280      branch-misses             #    0,22% of all branches        

           0,144966969 seconds time elapsed
           
**set**

     Performance counter stats for 'python3 perf.py':

            369,786395      task-clock (msec)         #    0,999 CPUs utilized          
                     0      context-switches          #    0,000 K/sec                  
                     0      cpu-migrations            #    0,000 K/sec                  
               108 584      page-faults               #    0,294 M/sec                  
         1 175 946 161      cycles                    #    3,180 GHz                    
         2 086 554 968      instructions              #    1,77  insn per cycle         
           422 531 402      branches                  # 1142,636 M/sec                  
               768 338      branch-misses             #    0,18% of all branches        

           0,370103043 seconds time elapsed

I do not see here any obvious reason for these poor performances. The code with `ctypes` has less page-faults than the code with `set` and the same number of branch-misses than the two others. The only thing I see is that there are more instructions and branches (but we still don't know why) and more context switches (but it is certainly a consequence of the longer run time rather than a cause).

**Comment by lemire** [comment]
@Ezibenroc  That's useful.

I am guessing right now that what is hurting is the "star" operator. I don't know exactly how it is implemented, but I suspect it might not be designed for speed.

**Comment by lemire** [comment]
You can do a lot better this way:  ``x=(ctypes.c_uint32 * len(t))();x[:]=t;``.

**Comment by lemire** [comment]
I suggest using ``array.array``, see my PR 

https://github.com/Ezibenroc/PyRoaringBitMap/pull/11

**Comment by lemire** [comment]
With my PR, here are the results for this script

```python
import timeit
setup="from array import array; import pyroaring; import ctypes; t = [i for i in range(1000000)];"
print(timeit.timeit(stmt='x=pyroaring.BitMap(t)',setup=setup,number=100))
print(timeit.timeit(stmt='set(t)',setup=setup,number=100))
```

```
1.4755003000609577
2.810183522757143
```

So, for sizeable lists, constructing a set takes longer. The break-even point seems to be around 10000 items. For small lists, a set is going to be faster though maybe just be a factor of 2 or 3.

**Comment by Ezibenroc** [comment]
Thank you.

Here is my results with the same Python code as you:

**Non amalgamated CRoaring**

    4.63016948600125
    3.1604399180014298

**Amalgamated CRoaring**

    1.6751420559994585
    3.2156787809999514

So, it confirms that the amalgamation has a non negligible impact on performances.

**Comment by Ezibenroc** [comment]
For the record, I asked the question on [stackoverflow](http://stackoverflow.com/questions/39225263/why-is-ctypes-so-slow-to-convert-a-python-list-to-a-c-array).

**Comment by lemire** [comment]
@Ezibenroc  Didn't you just mark my answer as the accepted one? ;-)

(One might say we were conspiring to earn SO points, but, we worked independently.)

**Comment by Ezibenroc** [comment]
I just wanted to leave a trace on Github :)

**Comment by lemire** [comment]
@Ezibenroc 

Please update to CRoaring version 0.2.1. You should see a significant performance boost (over 30%).

(The function that maps a pointer to a bitmap was never meant to be very fast. I did a little bit of work and was immediately able to boost the performance.)

**Comment by lemire** [comment]
@Ezibenroc  How did you build the version with amalgamation? I am surprised by your numbers and I'd be interested in checking them out.

I think that anything more than a 2x boost on this particular test is somewhat suspect. Amalgamation helps but I don't expect it to boost the performance by 3x except in some narrow cases.

**Comment by Ezibenroc** [comment]
To build with amalgamation:
```bash
python3 -m pyroaring install --user
```

It will add an entry in your shell configuration file. Then, you have to apply the changes by either opening a new terminal or using `source`:
```bash
source ~/.zshrc
```

I did not test the installation on a mac, I would be happy to have any feedback.

The installation script can be found [here](https://github.com/Ezibenroc/PyRoaringBitMap/blob/master/pyroaring/__main__.py). In short, it firstly clones CRoaring repository, then does the following:
```bash
bash amalgamation.sh
gcc -march=native -O3 -std=c11 -shared -o libroaring.so -fPIC roaring.c
```

**Comment by lemire** [comment]
I have not investigated the performance difference... but what I like is that it lifts the ``cmake`` requirement. The installation works well, I sent you a small bug fix for Macs.

**Comment by lemire** [comment]
It seems that CRoaring has relatively slow constructors due to too many calls to ``malloc``. I am working on optimizing it further which should improve these numbers further.
