### ISSUE TITLE
Publish type annotations

### ISSUE THREAD

**Issue by PeterJCLaw** [Ezibenroc/PyRoaringBitMap#105]
It would be great if pyroaring published type annotations, to enable type checking with e.g: mypy of usages.
I don't know if Cython supports automatically generating stubs from the source files, if it does that would be a neat way of keeping them in step.

**Comment by PeterJCLaw** [comment]
Looks like there may be a number of tools which support auto-generation: https://github.com/cython/cython/pull/3818#issuecomment-1666687625. Not sure I know enough about the Cython side to know which might be compatible though.

**Comment by Ezibenroc** [comment]
Yes, that would be great, especially if the types are auto-generated!
