### ISSUE TITLE
TypeError raised for equality comparison with other object

### ISSUE THREAD

**Issue by PeterJCLaw** [Ezibenroc/PyRoaringBitMap#107]
While rich comparisons (such as `<`, `<=`, etc.) are often limited per type in Python, it is (I believe) generally expected that simple equality comparisons will work for any pair of objects -- even if the result is always `False`.

Currently `pyroaring.AbstractBitMap` will raise an error (usually `TypeError`) when compared to an incompatible type:
```
TypeError: Argument 'other' has incorrect type (expected pyroaring.AbstractBitMap, got int)
```
Comparison to `None` raises an `AttributeError`:
```
AttributeError: 'NoneType' object has no attribute 'copy_on_write'
```

Discovered while working on https://github.com/Ezibenroc/PyRoaringBitMap/issues/105.

**Comment by Ezibenroc** [comment]
Fully agree! Do you want to make a PR? I can make it otherwise.
