### ISSUE TITLE
Segfault when serializing with pickle/cPickle

### ISSUE THREAD

**Issue by David-R-Walker** [Ezibenroc/PyRoaringBitMap#14]
Pickling and unpickling a BitMap object results in a double-reference to the \_\_obj\_\_, and a segfault due to a double-free, and/or segfault when unpickling if the original object has been freed, or is unpickled in a new process.

BitMap should support \_\_getstate\_\_() / \_\_setstate\_\_() for compatibility with Python pickle protocol.

Please see pending pull request for a new unit test that reproduces the problem, and a fix.

**Comment by Ezibenroc** [comment]
Fixed in #15
