### ISSUE TITLE
Upgrade to CRoaring 0.2.11

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#16]
https://github.com/RoaringBitmap/CRoaring/releases/tag/v0.2.11

Pregenerated unity builds...

https://github.com/lemire/CRoaringUnityBuild

**Comment by Ezibenroc** [comment]
I am not sure to understand.
When you install Pyroaring (with `python -m pyroaring install --user`), the branch `master` of CRoaring repository is pulled, then the library is amalgamated and compiled. So there is no need to use the CRoaringUnityBuild here.

**Comment by lemire** [comment]
Sorry, I meant "run tests anew". I did and it is fine. Closing.

**Comment by Ezibenroc** [comment]
Oh, ok. I just restarded a build on [Travis](https://travis-ci.org/Ezibenroc/PyRoaringBitMap/builds/183642629), everything is fine.

**Comment by lemire** [comment]
@Ezibenroc  I am moderately paranoid. ;-)

**Comment by lemire** [comment]
I have opened a new issue regarding 0.2.12: we now have "standard" iterators which may prove useful. Maybe.
