### ISSUE TITLE
Segmentation fault when using threading module

### ISSUE THREAD

**Issue by Ezibenroc** [Ezibenroc/PyRoaringBitMap#2]
The following code produces a segmentation fault:

```python
import threading
from pyroaring import BitMap

def compute():
    bm = BitMap()

t = threading.Thread(target=compute)
t.start()
t.join()
```

It seems that the crash happens when the destructor of `BitMap` is called.
If we call any method of the `BitMap` object after its initialization (e.g. a call to `len(bm)`), then the crash is produced by this call.

Nothing bad happens if the `BitMap` is created before the creation of the thread.
For instance, the following code exits without error:
```python
import threading
from pyroaring import BitMap

bm = BitMap()

def compute():
    bm.add(42)

t = threading.Thread(target=compute)
t.start()
t.join()
print(bm)
```

**Comment by lemire** [comment]
Unfortunately, I was able to verify the problem...

Since CRoaring is currently entirely single-threaded... I am somewhat perplexed as to why threading would suddenly cause problems with such simple code.

**Comment by Ezibenroc** [comment]
I reproduced this problem with a very simple code which does not use CRoaring, so I do not think the problem come from here.

I just asked a question on Stackoverflow : http://stackoverflow.com/questions/37953055/segmentation-fault-when-using-ctypes-and-threading

**Comment by lemire** [comment]
Ok. So don't allocate the bitmaps within the threads?

**Comment by Ezibenroc** [comment]
Fixed by https://github.com/Ezibenroc/PyRoaringBitMap/commit/ef75848fbe66745d8133bb3ef7b01bc6f06d13a7

The problem was that the return and argument types of the CRoaring functions was not declared on the Python side.
