### ISSUE TITLE
Manual installation : missing command in README

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#25]
In the section on manual installation, you are assuming that ``git clone`` loads the submodules, which is not true. You can load them as...

```
git pull && git submodule init && git submodule update && git submodule status
```

Then and only then can you type

```
python setup.py install
```

Note that you may want to refresh the submodule...

```
git submodule foreach git pull origin master
git commit -a
git push
```

**Comment by Ezibenroc** [comment]
Good catch, thank you.
