### ISSUE TITLE
Is pyroaring safe for Gunicorn?

### ISSUE THREAD

**Issue by suzaku** [Ezibenroc/PyRoaringBitMap#26]
I'm using `pyroaring` with `Gunicorn` in `preload` mode, in which `Gunicorn` "load application code before the worker processes are forked".
I intend to load many `pyroaring` bitmaps and other big data structures in the *master* process and reuse them in multiple worker processes.
But something weird happens, the bitmaps in the worker processes seem to be polluted and each worker process return different kind of random results.
When `Gunicorn` restart worker processes, they start to return valid results again.
The only operations I use are `&` and `|`, so I believe it should be read-only.

**Comment by lemire** [comment]
Presumably, you pass the bitmaps to the Process object using a Value or Array? 

Can you share a code sample?

**Comment by suzaku** [comment]
On start of the master process, before forking workers, I load some data from the local file system.
Among the data are some inverted indices in which the indices are stored as normal Python sets.
Then I iterate over the inverted indices and replace each sets with the `BitMap` version with code like:

```python
for k, v in inverted_index.iteritems():
      inverted_index[k] = BitMap(v)
```

Now I assume that the memory occupied by these sets would be reused by the worker processes, as long as they are not modified.

In the worker processes, I use the inverted indices in the following way:

```python
match = None
for i in key_words:
     indices = inverted_index.get(i, BitMap())
     if match is None
          match = indices
     else:
          match &= indices
```

I don't know how to trigger the issue.
When I start `Gunicorn` the same way on my development environment, I cannot reproduce the problem.
There are mainly two differences between the development and production environment I can think of:

1. MacOS VS. Linux
1. The access pattern

**Comment by suzaku** [comment]
I will try my best to figure out how to reproduce the issue.
Do you think there's anything to do with the `copy_on_write` parameter in the constructor of the `BitMap` class?

**Comment by suzaku** [comment]
I've figured out why. It's my fault.

**Comment by Ezibenroc** [comment]
Was your problem related to pyroaring? Maybe not a bug, but something not clear in the documentation that we could improve?

**Comment by suzaku** [comment]
@Ezibenroc 
Before switching to `BitMap`, I'm creating new `set`s from `list`s every time, so my code above is OK.
After switching to `BitMap`, I changed my inverted indices a little bit by storing `BitMap`s instead of creating new ones every time. **This** change made my code buggy.

```python
match = None
for i in key_words:
     indices = inverted_index.get(i, BitMap())
     if match is None
          match = indices  # <-- match is assigned the first BitMap
     else:
          match &= indices # <-- &= is used and the first BitMap is updated in place every time
```
