### ISSUE TITLE
Failed to unpickle BitMap across Python 2 and 3

### ISSUE THREAD

**Issue by suzaku** [Ezibenroc/PyRoaringBitMap#27]
When I have to load Python2-pickled objects in Python 3 environment, I can often do it by setting `encoding="latin1"` like this:

```python
pickle.load(f, encoding='latin1')
```

But when using the same trick with objects that contained `pyroaring.BitMap`, I get the following error:

```python
pyroaring.pyx in pyroaring.BitMap.__setstate__()

TypeError: expected bytes, str found
```

**Comment by Ezibenroc** [comment]
Thank you for reporting this, the issue should be fixed now.

**Comment by suzaku** [comment]
@Ezibenroc 

Thanks for the fix.

I've already fixed the compatibility issue using the `serialize` and `deserialize` methods of the `Bitmap` class.
I've also observed that, after switching to the new serialization approach, I also fixed some memory leaking issue by accident.
Maybe the memory leak was related to deserializing a bitmap using pickle.
