### ISSUE TITLE
run_optimize

### ISSUE THREAD

**Issue by phaethon** [Ezibenroc/PyRoaringBitMap#29]
Why run_optimize is not exposed as a method of BitMap? Is there some issue why it is not trivial?
Evaluating pyroaring for potential use in http://github.com/phaethon/kamene for indexing network packets.

**Comment by Ezibenroc** [comment]
I recently added this method, see 621b7f4873d0529c2ea0cbe149cfc6c51853fd47
I will upload a new release to pypi soon.
Note that  you may already have some run containers in your bitmaps, have you checked with the method `get_statistics`?

**Comment by Ezibenroc** [comment]
Release [0.2.0](https://pypi.org/project/pyroaring/0.2.0/) is available on Pypi.

Now, `BitMap` objects have a method `run_optimize` that you can call.
```python
bm = BitMap()
for i in range(100):
    bm.add(i)
print(bm.get_statistics()['n_values_run_containers'])  # 0
bm.run_optimize()
print(bm.get_statistics()['n_values_run_containers'])  # 100
```
Note that this method is called automatically when a new BitMap is instanciated. You can disable this behavior by passing the argument `optimize=False` to the constructor.
```python
bm = BitMap(list(range(100)))
print(bm.get_statistics()['n_values_run_containers'])  # 100 already
bm = BitMap(list(range(100)), optimize=False)
print(bm.get_statistics()['n_values_run_containers'])  # 0
```
