### ISSUE TITLE
Python amalgamation script creates a roaring.cpp file whereas original (bash) amalgamation script creates a roaring.c file

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#31]
CRoaring is a C library. If you take the amalgamated files with our bash script, you can build a working Visual Studio project with them...

https://github.com/lemire/croaringfun

However, it looks like you replaced the bash script with a Python script... nothing wrong with that per se... except that the Python script generates a roaring.cpp file, not a roaring.c file.

Though C is almost a subset of C++, that's not quite true. By using the cpp extension, you are hinting that CRoaring is C++ code, and that's not quite correct.

So I suggest that the Python amalgamation script be made to produce a roaring.c file, instead of a roaring.cpp file. This should ease support for Visual Studio.

**Comment by Ezibenroc** [comment]
For the record, I switched from C to C++ in c7131495de42a160ff92a2bb468ac63b84ecd71d

If I remember correctly, I had some troubles with the compilation on OSX, as the Cython sources are compiled in C++ but the CRoaring sources are in C.

I am considering switching everything to C. The only C++ features used in pyroaring are the `vector` and `bool` types, which could be easily replaced.
