### ISSUE TITLE
pyroaring doesn't adhere to python set conventions

### ISSUE THREAD

**Issue by urdvr** [Ezibenroc/PyRoaringBitMap#37]
Really nice package, I'm using it in (soon-to-be) production code!

The current behavior (checkout `3c3e3be`) is different from python native sets and so you can't really use pyroaring as a drop-in replacement.

intersection and union should be instance methods and not class methods:
```python
from pyroaring import BitMap
set1 = {3, 18}
set2 = {3, 27, 42}
assert (set1 & set2) == set1.intersection(set2)  # succeeds

bm1 = BitMap([3, 18])
bm2 = BitMap([3, 27, 42])
assert (bm1 & bm2) == bm1.intersection(bm2)  # fails
```
Some methods aren't implemented:
```python
assert (set1 - set2) == set1.difference(set2) #succeeds
assert (bm1 - bm2) == bm1.difference(bm2) #object has no attribute 'difference'

assert not set1.issuperset(set2) #succeeds
assert not bm1.issuperset(bm2) #object has no attribute 'issuperset'
... #and so on
```
Changing these behaviors would be a breaking change and it's understandable if you don't want to break existing code. But if there's any interest to move towards compatibility with python native sets, I'd be willing to contribute.

**Comment by Ezibenroc** [comment]
Thank you for raising this issue!

> intersection and union should be instance methods and not class methods:

True. Note that the `set` class supports both the usage as a class method and as an instance method. For instance, the following works:
```python
set1 = {3, 18}
set2 = {3, 27, 42}
set1.intersection(set2) == set.intersection(set1, set2)
```
I am not sure on the best way to do this. Something like this seems to work:
```python
class A:
    def foo(self, *args):
        if not isinstance(self, type): # this is called as an instance method
            args = (self,) + args
        print(args)
```

-----

> Some methods aren't implemented:

Also true. From [Python's documentation](https://docs.python.org/3.6/library/stdtypes.html#set), the (hopefully exhaustive) list of methods that are currently missing in pyroaring is:
- `isdisjoint`
-  `issubset`
- `issuperset`
- `difference`
- `symmetric_difference`
- `copy`
- `difference_update`
- `symmetric_difference_update`
- `clear`

-----

> Changing these behaviors would be a breaking change and it's understandable if you don't want to break existing code.

It would not be a breaking change if we manage to make the methods like `intersection` work both as instance and class methods.

> But if there's any interest to move towards compatibility with python native sets, I'd be willing to contribute.

Sure, any contribution will be appreciated!
