### ISSUE TITLE
MacOS support is missing

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#4]
With a script such as this one...

```python
from pyroaring import BitMap
bm = BitMap()
bm.add(1)
print(bm[0])
print(len(bm))
for i in bm:
  print (i)
print("got bm"+str(bm))
bm2 = BitMap()
bm2.add(2)
print(bm==bm2) #crashes
```

I get the crash (segfault) at the ``bm==bm2`` function call. 

In the code, I was able to trace down the fault to this line ``libroaring.roaring_bitmap_equals(self.__obj__, other.__obj__)``.

**Comment by Ezibenroc** [comment]
Does it still crash after https://github.com/Ezibenroc/PyRoaringBitMap/commit/ef75848fbe66745d8133bb3ef7b01bc6f06d13a7 ?

**Comment by Ezibenroc** [comment]
There was still a problem, hopefully fixed in https://github.com/Ezibenroc/PyRoaringBitMap/commit/f171e033b7d734b920f15d1391ad220442445d15. Are the tests passing now on your Mac?

**Comment by lemire** [comment]
@Ezibenroc 

I have updated the description. I get further, but it still crashes.

**Comment by Ezibenroc** [comment]
I forgot the type declarations for `roaring_bitmap_equals`. Fixed in https://github.com/Ezibenroc/PyRoaringBitMap/commit/7486481d9bac24630434330552ed9ad33e9146f0

**Comment by lemire** [comment]
Fixed.

```bash
$ python3 test.py
...................
----------------------------------------------------------------------
Ran 19 tests in 76.342s

OK
```
