### ISSUE TITLE
Push released wheels to Pypi

### ISSUE THREAD

**Issue by pombredanne** [Ezibenroc/PyRoaringBitMap#46]
It would be great if you could push the released wheels also to Pypi.

**Comment by Ezibenroc** [comment]
For reference, I think you are refering to these two commits:
- https://github.com/pombreda/thirdparty-manylinux/commit/d02f4f4c06416a3bee9c02fa47d78901ca043f97
- https://github.com/pombreda/thirdparty/commit/4d5289b7f2c30946574985fe55ab65a5a95003a5

My main concern is that providing the wheels in Pypi would be worse in terms of performance and portability. See my comment in another issue: https://github.com/Ezibenroc/PyRoaringBitMap/issues/45#issuecomment-468191943

One nice solution would be to solve this: https://github.com/RoaringBitmap/CRoaring/issues/113

**Comment by lemire** [comment]
The upstream problem is not hard to solve... if someone wants to tackle it, I can help.

(I might get to it, but not immediately.)

**Comment by danpalmer** [comment]
@Ezibenroc would it be possible to provide a wheel that's as compatible/portable as possible, at the cost of performance, and then provide separate packages (maybe `pyroaring-avx` or `pyroaring[avx]`) that are more optimised and less compatible?

While it's possible to reference the wheels directly, that loses out on the ability to track new versions, security releases, etc if we're not referencing a PyPI version.

**Comment by lemire** [comment]
Though it is not ready yet, we shall have runtime dispatching in the CRoaring soon enough... I wrote the implementation today... We just need better testing and evaluation.

https://github.com/RoaringBitmap/CRoaring/pull/285

In effect, this should make @danpalmer 's proposal both obsolete and unnecessary.

**Comment by Ezibenroc** [comment]
@lemire great news!

@danpalmer I think we will wait a bit then, as runtime dispatching would allow for the best of both worlds.

**Comment by lemire** [comment]
It will work with GCC, clang (version 9 and up) and Visual Studio (2017 and up). For older clang compilers, there is a bug (in the compiler) preventing me from implementing runtime dispatching.

**Comment by Ezibenroc** [comment]
At last the wheels are on Pypi, thanks to https://github.com/RoaringBitmap/CRoaring/pull/285

If you have a recent enough version of pip, you can now install a pyroaring wheel simply by using the command:
```sh
pip install pyroaring
```
