### ISSUE TITLE
Verify include paths and installation instructions

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#5]
PyRoaringBitMap may need to be updated following this PR:

https://github.com/RoaringBitmap/CRoaring/pull/43

**Comment by Ezibenroc** [comment]
I restarted a build on Travis, everything seems to be ok: https://travis-ci.org/Ezibenroc/PyRoaringBitMap/builds/141873389

**Comment by lemire** [comment]
Ok. If you think it is fine, feel free to close this issue. One alternative to your installation instructions would be to first install CRoaring system-wide with a ``make install``.

**Comment by Ezibenroc** [comment]
Sure, I have updated the README to add this alternative (see https://github.com/Ezibenroc/PyRoaringBitMap/commit/2187d52c12a2bc44891ea987d649ed571065366c).
