### ISSUE TITLE
Make it possible to build without march

### ISSUE THREAD

**Issue by nanonyme** [Ezibenroc/PyRoaringBitMap#50]
Currently building this package into host-agnostic containers is painful in multi-arch scenario as you only have option to not set ARCHI (results in --march=native) or set ARCHI (results in --march=$ARCHI). This results in either needing to patch this project or set arch-dependent values for ARCHI to reset the defaulta. 

It would be nice to have an option for --march not to be set at all.

**Comment by lemire** [comment]
It will be easy to solve this issue once we solve the upstream issue https://github.com/RoaringBitmap/CRoaring/issues/113

(We now know how to do it exactly, it is just a matter of getting it done.)

**Comment by nanonyme** [comment]
Hmm, why would that linked ticket be relevant? We just want to build more generic binaries. We don't need the optimizations.

**Comment by lemire** [comment]
@nanonyme Can't you just do `ARCHI=generic` if you don't care about performance?

**Comment by nanonyme** [comment]
That's not supported by gcc. Only mtune supports generic, march does not.

**Comment by lemire** [comment]
@nanonyme Point taken. My proposal was incorrect.

The README suggests `x86-64`. Won't that work?

**Comment by nanonyme** [comment]
That's only if you're on x86-64. That's not a working solution if you're trying to build pyroaring for many target architectures. The only way to fix this is really to remove the parameter completely with some option to setup.py, gcc doesn't support any other way to reset to default.

**Comment by lemire** [comment]
Makes sense. I am not the maintainer, but maybe you could go with a PR to make things precise... because, if I understand what you are saying is that if ARCHI is not set, you would prefer that `--march` not be used. That's literally a single line to change.

**Comment by nanonyme** [comment]
I think maintainer considers it desirable by default native build and this happens when ARCHI is unset. I can make proposal as PR at some point.

**Comment by Ezibenroc** [comment]
@nanonyme so you want to remove the `--march` flag when building the package. Would something like that be ok for you to build a wheel?
```sh
ARCHI=generic python setup.py bdist_wheel
```
I do not know which keyword would be the best here, it should not conflict with existing `--march` keywords. Otherwise, we could use yet another environment variable, but I think it is a bit too much.

If you are ok with the solution, that's just two lines around here: https://github.com/Ezibenroc/PyRoaringBitMap/blob/266705ef5f94b02d165535fea56ead6baecebc51/setup.py#L92-L95
Do you want to make a PR?

**Comment by nanonyme** [comment]
That sounds like a reasonable solution to me.

**Comment by Ezibenroc** [comment]
Thanks!
