### ISSUE TITLE
bm Illegal Instruction

### ISSUE THREAD

**Issue by Wish000** [Ezibenroc/PyRoaringBitMap#52]
Hello! I'm using the PyRoaringBitMap (the latest 0.2.8 version).
In Python2.7 shell on Linux, when I type the code like this:
`from pyroaring import BitMap`
`bm = BitMap()`
`bm`
 the error "Illegal Instruction" occurred and python shell exited.
On mac it's ok. However, on Linux python 2.7 when running Spark job, it fails every time without any logs.

Could you give me some suggests? Thank you!

**Comment by lemire** [comment]
@Wish000 What is your processor? Is this a recent processor (2013 and better, starting with Intel Haswell), or something older?

**Comment by Wish000** [comment]
My CPU is the "Common KVM processor". They're VM servers... On Python 3.6 it's OK.

**Comment by Ezibenroc** [comment]
How did you install pyroaring exactly? Are you saying that this problem only happens with root and not with other users?

**Comment by Wish000** [comment]
Sorry, I had tested later. The problem is not related to users. Since the problem occurs randomly, it makes me judge the error. 
I installed pyroaring from wheels as "pip install http://xxx.whl". In this case the problem often occurs. If I install it by "pip install pyroaring -i xxx" as now, it's working well ! 
Thank you two!

**Comment by Ezibenroc** [comment]
Well, if you install it from a wheel, the code is already compiled to machine instructions. In this case, it is expected to work only for some specific architectures.
The recommend installation (`pip install pyroaring`) will compile the code for your machine, so you should not have any illegal instructions in this case.

I am leaving the issue open, as it would probably be safer to provide more generic wheels (e.g., with #51).

**Comment by lemire** [comment]
@Ezibenroc Could the issue be documented in the README? A warning and explanation there could go a long way toward alleviating the issue.

**Comment by Wish000** [comment]
Well, I see. Thx a lot!

**Comment by lemire** [comment]
This issue should be revisited.

**Comment by Ezibenroc** [comment]
I think this was solved with https://github.com/Ezibenroc/PyRoaringBitMap/issues/69, I am closing the issue, feel free to reopen if you stumble again on such problems.
