### ISSUE TITLE
make use of the new andNot functions

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#6]
CRoaring now has builtin support for andNot 

https://github.com/RoaringBitmap/CRoaring/blob/1332e05a07e5663ee7fe32e6f6141322eb8633ff/include/roaring/roaring.h#L143

**Comment by Ezibenroc** [comment]
Thank you for the update, fixed in https://github.com/Ezibenroc/PyRoaringBitMap/commit/aa552c3d48ccfc741117ac79b234e292c67e933f.
