### ISSUE TITLE
Upgrade hypothesis

### ISSUE THREAD

**Issue by Ezibenroc** [Ezibenroc/PyRoaringBitMap#60]
The [hypothesis](https://pypi.org/project/hypothesis/) testing framework has made quite a lot of updates with breaking changes. They are currently at version 5.35 whereas this project requires a version lower than 3.60.

**Comment by urdvr** [comment]
Hi, 

Are pull requests welcome for this issue? I have a version of test.py that I tested up to version 5.29 (the latest version available in conda).

**Comment by Ezibenroc** [comment]
Wow, I had no idea that someone already did the work, sure your pull request is very welcome :+1: 

Did you have to get rid of some tests?

**Comment by urdvr** [comment]
I didn't remove any tests. Most changes were about removing deprecated settings or moving imports around.

I found a failing case for `test_next_set_bit` and fixed the test.

**Comment by Ezibenroc** [comment]
Awesome, thanks a lot!
