### ISSUE TITLE
intersection_len() and union_len() ?

### ISSUE THREAD

**Issue by remiadon** [Ezibenroc/PyRoaringBitMap#64]
[This pure Cython implementation](https://github.com/andreasvc/roaringbitmap) provides [intersection_len](https://roaringbitmap.readthedocs.io/en/latest/#roaringbitmap.RoaringBitmap.intersection_len) and [union_len](https://roaringbitmap.readthedocs.io/en/latest/#roaringbitmap.RoaringBitmap.union_len) methods.

Those methods have better runtime and save memory compared to calling the intersection/union and then accessing the length.
I wonder if you plan to implement such methods. 

Regards

**Comment by Ezibenroc** [comment]
These methods also exist in pyroaring, they are called `intersection_cardinality` and `union_cardinality`:

```python
from pyroaring import BitMap
bm1 = BitMap([2, 3, 5, 7, 11])
bm2 = BitMap([0, 1, 2, 3, 4])
print('Intersection:', bm1.intersection_cardinality(bm2))
print('Union:', bm1.union_cardinality(bm2))
```
Result:
```
Intersection: 2
Union: 8
```

Likewise, there are similar methods for other operations (e.g., `difference_cardinality` and `symmetric_difference_cardinality`), you have the full list in the [documentation](https://pyroaringbitmap.readthedocs.io/en/stable/).
