### ISSUE TITLE
Migrate from Travis (and Appveyor?) to Github Actions

### ISSUE THREAD

**Issue by Ezibenroc** [Ezibenroc/PyRoaringBitMap#68]
Travis has became really slow lately, a job can literally be queued for hours before being scheduled. Also, Github Actions have some pretty nice features.

Another great point in favor of Github Actions is that they support Windows, so we could stop using Appveyor and have a single CI.

**Comment by lemire** [comment]
I have had good luck with GitHub actions.

**Comment by Ezibenroc** [comment]
Commit ca8687454a4332bb54bb0616226797882f2235bb adds github actions, with exactly the same tests that were done on Travis and Appveyor. There still misses the deployment step when a new release is made.

**Comment by Ezibenroc** [comment]
The release part is also done with github actions now, with the automatic upload of wheels to both github and pypi.
