### ISSUE TITLE
Consider updating to CRoaring 0.3.1

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#69]
The new version brings runtime dispatching so that if you are building with gcc, clang 9 or better, visual studio 2017 or better, the library will automatically use some AVX-optimized (or BMI-optimized) routines when the underlying processor reports that it supports AVX.

You may still be getting better performance if you compile with `-march=native` and some of our optimizations are only enabled when compile-time setting targets a recent x64 processor. So you do not get "the best of all worlds", there is still a tradeoff between convenience and performance.

However, what v0.3.1 brings is a better performance tradeoff for people who want the convenience of a generic build.

**Comment by lemire** [comment]
It should be 0.3.1.

**Comment by lemire** [comment]
Maybe this is solved.

**Comment by Ezibenroc** [comment]
Yes, solved with pyroaring 0.3.0, closing the issue, thank you.
