### ISSUE TITLE
SegFault with 2-parameter constructor

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#7]
I am not sure what the two parameter constructor is supposed to be... but I think I generate a segmentation fault a bit too easily...

```python
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b[1]
KeyboardInterrupt
>>> import pyroaring
>>> x=pyroaring.BitMap(1,4)
>>> x
Segmentation fault (core dumped)
```

**Comment by Ezibenroc** [comment]
The parameter `obj` of the constructor is not intended to be used by the user. It is used in pyroaring to create a BitMap from a pointer to a `roaring_bitmap_t` (for instance in https://github.com/Ezibenroc/PyRoaringBitMap/blob/master/pyroaring.py#L105).
In a language like Java or C++, I would have used a private constructor for this.

I added a verification in the constructor to check for your example: https://github.com/Ezibenroc/PyRoaringBitMap/commit/36fc9882004c9b8ab02dcece5fc68441ce9bf4ea
Your example now raises an exception. To produce the same bug, you would have to call `BitMap(None, 4)` or `BitMap(obj=4)` which I think is unlikely. I am note sure there is a solution that will always prevent such bug (even if the constructor was safe, you could still overwrite the attribute `__obj__` of the BitMap).

I should write a documentation for pyroaring to prevent such issues.

**Comment by Ezibenroc** [comment]
I think that we can close now. Feel free to reopen if you disagree with the solution.
