### ISSUE TITLE
Implement "in place" binary operators on `FrozenBitMap` (to match `frozenset`)

### ISSUE THREAD

**Issue by PeterJCLaw** [Ezibenroc/PyRoaringBitMap#75]
For example:
``` python
In [1]: a = ref = frozenset(range(3))

In [2]: a
Out[2]: frozenset({0, 1, 2})

In [3]: a &= frozenset([3, 1, 4])

In [4]: a
Out[4]: frozenset({1})

In [5]: ref
Out[5]: frozenset({0, 1, 2})
```
(Also for `|=`, `^=` and possibly others)

It might be good if `FrozenBitMap` supported the same API.

**Comment by Ezibenroc** [comment]
Sure, whenever you want!

I did not test, but it might be enough to simply remove the methods from the `FrozenBitMap`. I think that if the in-place methods (like `__iand__`) are not implemented, Python automatically calls the not in-place version (like `__and__`).
Modifying the [tests](https://github.com/Ezibenroc/PyRoaringBitMap/blob/master/test.py#L826) will take a bit longer, but this should be straightforward (e.g. something like the piece of code you wrote).
