### ISSUE TITLE
Packaging for newer Python versions - proposal/offer of help

### ISSUE THREAD

**Issue by SamHames** [Ezibenroc/PyRoaringBitMap#78]
First off - thanks for the package, it's been really great to use.

This proposal has been motivated by doing some investigations with Python 3.11 - currently installation isn't possible from the sdist on PyPI because of a change in Python internals which means the Cython generated file in the sdist doesn't work with Python 3.11.

I'd like to offer to put in some maintenance time on the packaging and distribution side of things to make this library more accessible on recent python versions.

My very rough proposal of what I could do is:

1. Switch to using the new [release amalgamations](https://github.com/RoaringBitmap/CRoaring/releases) for croaring and remove the amalgamation code from this repository.
2. Streamline setup.py and the source distribution a bit:
	- add the cython source files to the source distribution
	- update the source installation procedure to compile the generated file, unless cython is available
3. Extend the existing CI/release actions to test and build wheels for newer Python's [^1]
4. Make a new release against the latest croaring.

I should add that I think all of the above is pretty straightforward, but I don't have a lot of experience at the C/Cython layer (part of the motivation for offering to help is because I want to learn more here).

[^1]: If this all goes smoothly I'd also be happy to take a go at moving the wheel building over to [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for a hopefully smoother and more comprehensive approach to building wheels.

**Comment by Ezibenroc** [comment]
Wow, that would be great, thanks! I completely agree that packaging is not ideal here, any help is very welcome.
Your proposal looks fine to me, I would merge that.

**Comment by Ezibenroc** [comment]
A few months ago I had some troubles building the Linux wheel (e.g. see [this build](https://github.com/Ezibenroc/PyRoaringBitMap/actions/runs/2393290612)). If I remember well, this was somehow due to a problem in the action [python-wheels-manylinux-build](https://github.com/RalfG/python-wheels-manylinux-build). I did not manage to fix this at the time, but maybe your proposal of using `cibuildwheel` could help us here!
