### ISSUE TITLE
Get SIGSEGV when bitmap.contains_range(start, end) is run

### ISSUE THREAD

**Issue by kcaashish** [Ezibenroc/PyRoaringBitMap#81]
`Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux`

There is a bitmap filled till 1900543. If I run a bitmap.contains_range(1900543, 1900545) I get a segmentation fault and cannot figure out why.

![image](https://user-images.githubusercontent.com/31175326/210707979-71509e4d-3545-408a-810a-6c955cc072b2.png)

**Comment by lemire** [comment]
I have reproduced the issue. I will check later today if the problem might be upstream.

**Comment by lemire** [comment]
Upstream (CRoaring) now has a test closely related to this issue, and we find no problem...
https://github.com/RoaringBitmap/CRoaring/blob/025d86759304ffeb8491cda6170f0323c544461b/tests/toplevel_unit.c#L1505

**Comment by lemire** [comment]
I can only reproduce the problem on my mac. It happens whether I install it from pip, or from source.

**Comment by kcaashish** [comment]
I am using this method to get empty slots available in a bitmap which can be filled with a particular sum of numbers.

```py
ShareNumber = int
MAX_SHARE_NUMBER = 1000000000000
SHARE_MULTIPLIER = 1

def get_slot(
    self, share_numbers: ShareNumber, start_num: int = 1, end_num: int = MAX_SHARE_NUMBER
) -> Tuple[ShareNumber, ShareNumber]:
    """Get the start and end share numbers which is available for the given total share numbers."""
    if share_numbers > MAX_SHARE_NUMBER:
        raise ValueError("Share number is too big.")
    for slot in range(start_num, end_num + 1, SHARE_MULTIPLIER):
        slot_start = start_num
        slot_end = start_num + share_numbers

        if not self.bitmap.contains_range(slot_start, slot_end):
            if not self.bitmap.__contains__(slot_start):
                return slot_start, slot_end
            else:
                start_num += SHARE_MULTIPLIER
                continue

            start_num = slot_end
            slot = start_num
    return 0, 0
```

As a work around to it, I have done this, but is is terribly slow as the number keeps increasing in every iteration.
```py
    def get_slot(
        self, share_numbers: ShareNumber, start_num: int = 1, end_num: int = MAX_SHARE_NUMBER
    ) -> Tuple[ShareNumber, ShareNumber]:
        """Get the start and end share numbers which is available for the given total share numbers."""
        if share_numbers > MAX_SHARE_NUMBER:
            raise ValueError("Share number is too big.")
        for slot in range(start_num, end_num + 1, SHARE_MULTIPLIER):

            if not self.bitmap.__contains__(start_num):
                temp = start_num + SHARE_MULTIPLIER
                slot_found = True
                while temp <= start_num + share_numbers - SHARE_MULTIPLIER:
                    if self.bitmap.__contains__(temp):
                        slot_found = False
                        start_num = temp
                        slot = start_num
                        break
                    else:
                        slot_found = True
                        temp += SHARE_MULTIPLIER

                if slot_found:
                    return start_num, temp

            start_num += SHARE_MULTIPLIER
            slot = start_num

        return 0, 0
```

The returned value of this function is then used inside, self.bitmap.add_range(start, end).

Is there a better way of doing this or making it any faster?

**Comment by kcaashish** [comment]
In the test that you have added, instead of checking for (1, 1900545), which works for me and gives a False, please check for the range (1900543, 1900545). That is how I get the issue. 

![image](https://user-images.githubusercontent.com/31175326/210920978-de37a3d3-2bef-45f0-8a9c-728cf3d57cc4.png)

**Comment by lemire** [comment]
Yes. I quickly spotted my mistake, and updated the test to match yours... It is now part of our CI.

https://github.com/RoaringBitmap/CRoaring/blob/7c787c66db8baf344e8fb7e5acce68c938ac224a/tests/toplevel_unit.c#L1509

I expect that this PR will fix your issue: https://github.com/Ezibenroc/PyRoaringBitMap/pull/82

**Comment by lemire** [comment]
We should now bug [Ezibenroc](https://github.com/Ezibenroc) to entice him to review my PR.

**Comment by kcaashish** [comment]
Thank you @lemire. If this issue would be fixed this soon, it would help me massively. Requesting @Ezibenroc to review the PR and create new release of pyroaring.

**Comment by Ezibenroc** [comment]
This is (hopefully) fixed in the latest release, thank you for reporting the issue.
