### ISSUE TITLE
Consider a high-performance wrapper using the unity build

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#9]
CRoaring has a unity build:
https://github.com/RoaringBitmap/CRoaring#amalgamationunity-build

This avoids the nagging problem of dealing with a generic static library. Instead, you have a single header file and a single ``.c`` file that can be included directly. 

Using such a unity build, it should be possible to produce a higher-performance wrapper with good inlining. Moreover, the unity build could be included in this repository, making it super easy for people to proceed.

**Comment by lemire** [comment]
Here is a golang wrapper using the unity build. No need for a library.

**Comment by Ezibenroc** [comment]
Doing the unity build to improve performances is a god idea. But maybe we should automate this in CRoaring side? For instance, using the command `make` (or `make unity`) to run the script, and compile the resulting file.

About including the unity build in the repository, I agree that the installation would be easier, but I am not sure it is a good practice. We should not have to update pyroaring if CRoaring is updated but keeps its API as is. And we lose one of the benefits of dynamic libraries if every program that uses CRoaring has its own copy.

**Comment by lemire** [comment]
The idea of a unity build is that it comes as one .c file that the user of the code includes as such. This enables the compiler to inline all the code, for greater performance. So there is no point on the CRoaring side to compiling the unity build except maybe for testing purposes.

The approach we follow with the amalgamation script is identical to sqlite's approach. In turn, sqlite's unity builds are found just about everywhere. It is a sound, well-tested and robust practice.

We have dynamic libraries largely to save storage and memory but these points are not obviously beneficial here since CRoaring is tiny compared to today's machines...

Another point is that making your library as dependency-free as possible, and as easy to install as possible... makes it more useful...

**Comment by Ezibenroc** [comment]
I have thought a bit about the idea during the past few days and I am still not convinced.

Apart from SQLite, I did not find any evidences of the performance gained with code amalgamation. Do you know if there are some benchmarks or publications about this? Did you measure any improvements with CRoaring?
SQLite team measured improvements of 5 to 10%. It does not seem good enough to justify this.

Regarding the installation process, it is also not a big advantage, it just removes a few command lines (which could anyway be put in a small script for convenience).
The standards in software distribution seems to not embedding third party libraries with your software (Debian or Python packet management come to my mind here).

Therefore, I think I will rather work on a script to make the installation as easy as possible for the user. 

As a side question, why copying all the CRoaring files into two big files? Having a small file with a `#include` for each of the `.c` and `.h` files would have the same result from the compiler point of view, no?

**Comment by lemire** [comment]
I agree that performance is probably not sufficient motivation on its own.

What would be nice is for this library is to be installable as conveniently as possible by end-users. The current setup is nice but not automated and one needs cmake which is not available by default on many systems (e.g., Macs). The unity build removes cmake as a requirement.

Just including all the .c and .h might work, but I don't know how to do it. Do you have a way to pull it off?

**Comment by Ezibenroc** [comment]
We can now install CRoaring by calling `python -m pyroaring install`. I think the installation is now more convenient for the user, and it is based on amalgamation so we get the eventual gain of performances.

I am closing the issue, feel free to reopen if you disagree.

**Comment by lemire** [comment]
Fantastic. I think that the convenience is great.
