### ISSUE TITLE
curious about why there is no `contains` method

### ISSUE THREAD

**Issue by Huangvivi** [Ezibenroc/PyRoaringBitMap#91]
I see there is only `add_checked` method can judge whether an element included in the bitmap obj.
Should a pure checking method be implemented? without adding a new element

**Comment by Ezibenroc** [comment]
There is obviously a way to check membership:
```python
from pyroaring import BitMap
bm = BitMap([5, 8, 12])
print(5 in bm)  # True
print(6 in bm)  # False
```
In fact, most of the classic set operations are supported.

I will update the README to add this.
